wandb: Currently logged in as: hadars (autoconvnext). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_030751-ujfgqhqq
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run absurd-sunset-1
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/ujfgqhqq
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▅▄▄▄▄▄▄▄▄▄▄▃▃▃▃▃▃▃▃▂▂▂▂▂▁▁▁▁▁
wandb:  mae █▇▅▅▄▄▄▃▃▃▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb: loss 0.27136
wandb:  mae 0.85641
wandb: 
wandb: Synced absurd-sunset-1: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/ujfgqhqq
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_030751-ujfgqhqq/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_050907-1496jk6i
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run deep-field-2
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/1496jk6i
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▅▄▃▃▄▄▄▄▄▄▄▄▄▃▃▃▃▂▂▂▂▂▂▂▁▁▂▁▁
wandb:  mae █▇▆▅▄▄▃▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb: loss 0.2963
wandb:  mae 0.8646
wandb: 
wandb: Synced deep-field-2: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/1496jk6i
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_050907-1496jk6i/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_070954-2mo0ueyw
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run daily-sound-3
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/2mo0ueyw
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▅▄▄▃▃▃▃▄▄▃▃▃▃▃▃▂▂▂▂▂▁▁▁▁▂▁▁▁▁
wandb:  mae █▇▅▄▄▃▃▃▃▂▂▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb: loss 0.30192
wandb:  mae 0.86895
wandb: 
wandb: Synced daily-sound-3: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/2mo0ueyw
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_070954-2mo0ueyw/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_091100-1nvph4x1
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run lucky-rain-4
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/1nvph4x1
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb: loss █▅▃▃▃▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁
wandb:  mae █▇▅▅▄▄▃▃▃▂▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb: loss 0.33906
wandb:  mae 0.87394
wandb: 
wandb: Synced lucky-rain-4: https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/1nvph4x1
wandb: Synced 6 W&B file(s), 0 media file(s), 1 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221201_091100-1nvph4x1/logs
wandb: wandb version 0.13.5 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.4
wandb: Run data is saved locally in /home/s3092593/benchmarking_rl/wandb/run-20221201_111128-3maqh089
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run radiant-water-5
wandb: ⭐️ View project at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4
wandb: 🚀 View run at https://wandb.ai/autoconvnext/benchmark_final_impala_large_4_DQN_modern_Phoenix_model_15250000_0_impala_large_4/runs/3maqh089
--- Logging error ---
Traceback (most recent call last):
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 263, in _process
    self._hm.handle(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 130, in handle
    handler(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/handler.py", line 138, in handle_request
    logger.debug(f"handle_request: {request_type}")
Message: 'handle_request: stop_status'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/data1/s3092593/rlenv/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/data1/s3092593/rlenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 50, in run
    self._run()
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 101, in _run
    self._process(record)
  File "/data1/s3092593/rlenv/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 263, in _process
    self._hm.handle(record)
  File "/data1/s3092593/rlenv/lib/python3.8/si